name: Deploy ClarizaLook

on:
    push:
      branches: [ adding-assets ]
    workflow_dispatch:

jobs:
    build-site:
      runs-on: ubuntu-latest
    
      steps:
      - name: Use Node
        uses: actions/setup-node@v2

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node Dependencies
        run: |
          npm i

      - name: Build App
        run: |
          npm run build


      